#pragma once

namespace MATID
{
	enum ID { TRANS, ROT, SCALE, END };
}

namespace OBJID
{
	enum ID { BACKGROUND, PLAYER, ENEMY, PLAYER_BULLET, ENEMY_BULLET, MOUSE, EFFECT, UI, DRONE, END };
}
namespace PLAYER
{
	enum STATE {IDLE,ROLL,END};
}
namespace ENEMY
{
	enum STATE {ATTACK,BACK,END};
}

namespace BULLET
{
	enum TYPE { NORMAL, GUIDE, SHOTGUN, END };

	enum SUBWEAPON {CHARGE_0,CHARGE_1,CHARGE_2,CHARGE_3};
}

namespace EFFECT
{
	enum TYPE {ROCKET_PTFIRE, ROCKET_BOOM_PTFIRE,JET_PTFIRE,CHAGE_BEAM,END};
}
namespace BURNER
{
	enum STATE { IDLE, START, START_OFF, ACCEL, AFTER, MEGA, BURST,END };
}
namespace RENDERID
{
	enum ID { BACKGROUND,MOVE_BACKGROUND1, MOVE_BACKGROUND2, MOVE_BACKGROUND3, GROUND,BULLET,OBJECT,EFFECT, BURNER,UI,END};
}

namespace ANGLE
{
	enum STATE {LEFT,UPLEFT,UP,UPRIGHT,RIGHT,DOWNRIGHT,DOWN,DOWNLEFT,END};
}

namespace COLLIDER
{
	enum ID {PLAYER,PLAYER_SEARCH,ENEMY,PLAYER_BULLET,PLAYER_BULLET_BEAM,ENEMY_BULLET,EFFECT,END};
}

namespace SCROLL
{
	enum ID {LEFT,TOP,RIGHT,BOTTOM,END};
}